# This dockerfile provides an example of using the production image in a working stack
version: '2'

services:
  mariadb:
    image: mariadb:10.4
    hostname: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: hx4hjxqthfwbfsy5535u4agfdscm
  semaphore:
    image: stanchan/semaphore:prod-compose
    build:
      context: ./../../../
      dockerfile: ./deployment/docker/prod/Dockerfile
    volumes:
      - "./config/config.json:/etc/semaphore/config.json:ro"
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: hx4hjxqthfwbfsy5535u4agfdscm
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: cangetin
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
    depends_on:
      - mariadb
  semaphore_proxy:
    image: stanchan/caddy:1.0.1
    environment:
      CADDY_TLS_MODE: caddy_tls_selfsigned
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - semaphore
